# Generated by Django 4.2.2 on 2023-06-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=123.456, max_digits=9, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
